name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  plugin:
    name: plugin test with jdk8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - working-directory: ./plugin
        run: sbt "migrateSyntax sbt-plugin"
